from pathlib import Path
from html import escape

ROOT = Path(__file__).parent

services = [
    ('full-service','Полное обслуживание механизма','Разборка, очистка, смазка, сборка, регулировка и контроль работы механизма.','MECHANICAL SERVICE'),
    ('movement-repair','Ремонт механизма','Диагностика неисправности и восстановление узлов механических и кварцевых часов.','CALIBRE REPAIR'),
    ('polishing','Полировка и восстановление корпуса','Работа с полированными и сатинированными поверхностями корпуса и браслета.','CASE & FINISHING'),
    ('glass-replacement','Замена стекла','Подбор и замена стекла с последующей проверкой посадки и состояния корпуса.','CRYSTAL'),
    ('water-resistance','Проверка герметичности','Контроль герметичности после вмешательства и перед повседневной эксплуатацией.','PRESSURE TEST'),
    ('automatic-winding','Ремонт автоподзавода','Диагностика ротора и узлов автоматического подзавода.','AUTOMATIC'),
    ('chronograph','Хронографы и сложные механизмы','Работы со сложными калибрами требуют предварительной диагностики и согласования.','COMPLICATIONS'),
    ('restoration','Реставрация','Деликатное восстановление корпуса, элементов внешнего оформления и отдельных узлов.','RESTORATION'),
]

brands = [
    ('rolex','Rolex'),('patek-philippe','Patek Philippe'),('audemars-piguet','Audemars Piguet'),('vacheron-constantin','Vacheron Constantin'),
    ('breguet','Breguet'),('jaeger-lecoultre','Jaeger-LeCoultre'),('a-lange-soehne','A. Lange & Söhne'),('omega','Omega'),
    ('cartier','Cartier'),('blancpain','Blancpain'),('iwc','IWC Schaffhausen'),('zenith','Zenith'),('ulysse-nardin','Ulysse Nardin'),
    ('girard-perregaux','Girard-Perregaux'),('hublot','Hublot'),('panerai','Panerai'),('chopard','Chopard'),('piaget','Piaget'),
    ('franck-muller','Franck Muller'),('parmigiani','Parmigiani Fleurier'),('h-moser','H. Moser & Cie.'),('breitling','Breitling'),
    ('tag-heuer','TAG Heuer'),('tudor','Tudor'),('grand-seiko','Grand Seiko'),('longines','Longines'),('rado','Rado'),
    ('tissot','Tissot'),('maurice-lacroix','Maurice Lacroix'),('frederique-constant','Frederique Constant'),('oris','Oris')
]

works = [
    ('omega-seamaster-planet-ocean','Omega','Seamaster Planet Ocean','Опубликованный кейс мастерской'),
    ('corum-admirals-cup','Corum',"Admiral’s Cup",'Опубликованный кейс мастерской'),
    ('maurice-lacroix','Maurice Lacroix','Mechanical','Опубликованный кейс мастерской'),
    ('tissot','Tissot','Mechanical','Опубликованный кейс мастерской'),
]

faqs = [
    ('Сколько занимает диагностика?','Срок зависит от модели и характера неисправности. После первичного осмотра мастер сообщает, нужна ли углублённая диагностика и когда можно согласовать работы.'),
    ('Стоимость известна заранее?','До начала основных работ согласуются перечень вмешательств и стоимость. Если в процессе обнаруживается дополнительная неисправность, её не следует устранять без отдельного согласования.'),
    ('Можно ли обслуживать дорогие часы без официального сервиса?','Независимая мастерская не является официальным сервисным центром брендов. Возможность конкретной работы зависит от модели, состояния часов, доступности компонентов и требований владельца.'),
    ('Что происходит после ремонта?','После сборки проверяются работа механизма и те параметры, которые относятся к выполненной услуге. Для работ, затрагивающих корпус, может потребоваться дополнительный контроль герметичности.'),
    ('Нужно ли записываться заранее?','Для часов высокого класса предварительная запись удобнее: можно заранее описать модель и задачу, а мастерская подготовится к осмотру.'),
]

def rel_prefix(depth:int):
    return '../' * depth

def header(prefix=''):
    return f'''<header class="site-header">
  <div class="header-inner">
    <a class="brand" href="{prefix}index.html" aria-label="На главную">
      <span class="brand-main">Atelier 01</span><span class="brand-sub">Watch service · Moscow</span>
    </a>
    <nav class="main-nav" aria-label="Основная навигация">
      <a href="{prefix}services/">Услуги</a><a href="{prefix}works/">Работы</a><a href="{prefix}brands/">Бренды</a><a href="{prefix}atelier/">Мастерская</a><a href="{prefix}prices/">Цены</a><a href="{prefix}contacts/">Контакты</a>
    </nav>
    <div class="header-actions"><span class="header-phone">Петровка · Москва</span><a class="header-book" href="{prefix}contacts/">Записаться <span>↗</span></a><button class="menu-toggle" aria-label="Меню" aria-expanded="false"><span></span><span></span></button></div>
  </div>
</header>
<div class="mobile-menu"><nav><a href="{prefix}services/">Услуги</a><a href="{prefix}works/">Работы</a><a href="{prefix}brands/">Бренды</a><a href="{prefix}atelier/">Мастерская</a><a href="{prefix}prices/">Цены</a><a href="{prefix}contacts/">Контакты</a></nav><div class="mobile-menu-meta"><span>Petrovka · Moscow</span><span>Independent atelier</span></div></div>'''

def footer(prefix=''):
    return f'''<footer class="site-footer"><div class="container"><div class="footer-grid"><div class="footer-brand">WATCH SERVICE<br>ATELIER</div><nav class="footer-nav"><a href="{prefix}services/">Услуги</a><a href="{prefix}brands/">Бренды</a><a href="{prefix}works/">Работы</a><a href="{prefix}prices/">Цены</a></nav><div class="footer-meta"><a href="{prefix}atelier/">Мастерская</a><a href="{prefix}contacts/">Петровка · Москва</a><span>По предварительной записи</span></div></div><div class="footer-bottom"><span>© <span data-year></span> Independent Watch Atelier</span><span>Независимая мастерская. Не является официальным сервисным центром и не аффилирована с указанными производителями.</span></div></div></footer><div class="toast"></div>'''

def doc(title, description, body, depth=0):
    prefix = rel_prefix(depth)
    return f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#07090b"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="{prefix}assets/css/styles.css"></head><body>{header(prefix)}{body}{footer(prefix)}<script src="{prefix}assets/js/main.js"></script></body></html>'''

def breadcrumbs(items, prefix=''):
    parts=[f'<a href="{prefix}index.html">Главная</a>']
    for name, href in items:
        parts.append('·')
        parts.append(f'<a href="{href}">{escape(name)}</a>' if href else f'<span>{escape(name)}</span>')
    return '<div class="breadcrumbs">' + ''.join(parts) + '</div>'

def page_hero(title, label, depth=0, media='hero-poster.webp', breadcrumbs_html=''):
    p=rel_prefix(depth)
    return f'''<section class="page-hero"><div class="page-hero-media"><img src="{p}assets/images/{media}" alt=""></div><div class="container page-hero-content">{breadcrumbs_html}<div class="eyebrow">{escape(label)}</div><h1 class="display display-lg">{escape(title)}</h1></div></section>'''

# HOME
featured_brands = brands[:12]
service_items=''.join([f'''<a class="service-item" href="services/{slug}/" data-preview="assets/images/detail-0{(i%3)+1}.webp"><span class="index">{i+1:02}</span><h3>{escape(name)}</h3><div class="meta"><span>{escape(tag)}</span><span>↗</span></div></a>''' for i,(slug,name,desc,tag) in enumerate(services)])
brand_rows=''.join([f'''<a class="brand-row" href="brands/{slug}/"><span class="brand-no">{i+1:02}</span><span class="brand-name">{escape(name)}</span><span class="brand-tag">Service request ↗</span></a>''' for i,(slug,name) in enumerate(featured_brands)])
faq_html=''.join([f'''<div class="faq-item"><button class="faq-q" aria-expanded="false"><span>{escape(q)}</span><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-a-inner">{escape(a)}</div></div></div>''' for q,a in faqs])

home=f'''
<main>
<section class="hero"><div class="hero-media"><img src="assets/images/hero-poster.webp" alt=""><video autoplay muted loop playsinline poster="assets/images/hero-poster.webp"><source src="assets/videos/hero-watch.mp4" type="video/mp4"></video></div><div class="container hero-inner"><div class="hero-copy reveal"><div class="eyebrow">Independent watch service · Moscow</div><h1 class="display display-xl">Ошибка здесь<br>неуместна.</h1><p class="hero-sub">Диагностика, обслуживание и восстановление швейцарских часов. Независимая мастерская на Петровке.</p><div class="hero-actions"><a class="btn" href="contacts/">Записаться на диагностику <span class="btn-arrow">→</span></a><a class="btn ghost" href="works/">Смотреть работы <span class="btn-arrow">↘</span></a></div></div><div class="hero-bottom"><div class="hero-brands"><span>Rolex</span><span>Patek Philippe</span><span>Audemars Piguet</span><span>Vacheron Constantin</span><span>Omega</span><span>Cartier</span></div><div class="hero-scroll">Scroll to atelier</div></div></div></section>

<section class="section section-ivory"><div class="container intro-grid"><div class="eyebrow reveal">01 / Atelier</div><div><h2 class="display display-lg intro-statement reveal">Механика не терпит приблизительности.</h2><div class="intro-copy reveal"><p class="lead">Часы высокого класса требуют не громких обещаний, а точной диагностики, аккуратной работы и понятного согласования каждого вмешательства.</p><p class="copy">Мы перестраиваем привычную логику «сервисного центра» вокруг самого изделия: сначала состояние часов, затем решение, затем работа и контроль результата.</p></div></div></div></section>

<section class="section section-dark"><div class="container craft-grid"><div class="media-frame reveal"><img src="assets/images/watchmaker.webp" alt="Работа часовщика"><video autoplay muted loop playsinline poster="assets/images/watchmaker.webp"><source src="assets/videos/watchmaker.mp4" type="video/mp4"></video><div class="media-caption"><span>WATCHMAKER / HAND SERVICE</span><span>01</span></div></div><div class="craft-copy reveal"><div><div class="eyebrow">Craft / precision</div><h2 class="display display-md">Работа, которую видно только в макро.</h2><p class="copy">Под отвёрткой — доли миллиметра. В кадре — то, что обычно скрыто под крышкой: мосты, винты, зубья, посадки и следы предыдущего вмешательства.</p></div><div class="craft-mini"><figure><img src="assets/images/detail-01.webp" alt="Механизм часов"></figure><figure><img src="assets/images/detail-02.webp" alt="Работа с механизмом"></figure></div></div></div></section>

<section class="section section-dark" id="services"><div class="container"><div class="services-head"><div><div class="eyebrow reveal">02 / Services</div><h2 class="display display-lg reveal">Что мы делаем.</h2></div><p class="copy reveal">Не прячем сложные работы за россыпью одинаковых карточек. Каждая услуга — отдельный сценарий диагностики и согласования.</p></div><div class="services-layout"><div class="service-list reveal">{service_items}</div><div class="service-preview reveal"><img id="servicePreviewImage" src="assets/images/detail-01.webp" alt="Процесс обслуживания"><div class="service-preview-note"><span>Macro service view</span><span>Move over services</span></div></div></div><div style="margin-top:46px"><a class="btn" href="services/">Все услуги <span class="btn-arrow">→</span></a></div></div></section>

<section class="section section-navy"><div class="container"><div class="brands-head"><div><div class="eyebrow reveal">03 / Maisons</div><h2 class="display display-lg reveal">Часы, с которыми приходят не за «быстрым ремонтом».</h2></div><p class="copy reveal">На главной — только несколько мануфактур. Полный список вынесен отдельно, чтобы каждая марка могла получить собственную SEO-страницу без стены логотипов.</p></div><div class="brand-cloud">{brand_rows}</div><p class="brands-note">Независимая мастерская. Указание товарных знаков носит информационный характер и не означает официальную аффилиацию. Возможность конкретной работы, наличие компонентов и сроки подтверждаются после осмотра.</p><div style="margin-top:34px"><a class="btn" href="brands/">Все бренды <span class="btn-arrow">→</span></a></div></div></section>

<section class="section section-dark"><div class="container case-grid"><div class="case-copy reveal"><div class="eyebrow">04 / Selected case</div><h2 class="display display-md">Omega<br>Seamaster<br>Planet Ocean</h2><p class="copy">Кейс из текущего портфолио мастерской. В новой версии сайта история ремонта подаётся не одной картинкой и ценой, а как полноценная карточка работы.</p><div class="case-specs"><div class="case-spec"><span>Формат</span><span>Выполненная работа</span></div><div class="case-spec"><span>Диагностика</span><span>Добавить фактические данные после переноса карточки</span></div><div class="case-spec"><span>Результат</span><span>Без выдуманных показателей точности и герметичности</span></div></div><a class="btn ghost" style="margin-top:30px" href="works/omega-seamaster-planet-ocean/">Открыть кейс <span class="btn-arrow">↗</span></a></div><div class="case-media reveal"><img src="assets/images/detail-02.webp" alt="Часовой механизм"></div></div></section>

<section class="section section-dark"><div class="container"><div class="eyebrow reveal">Selected works</div><h2 class="display display-lg reveal" style="margin:24px 0 0">Не портфолио.<br>История вмешательства.</h2><div class="works-grid"><a href="works/omega-seamaster-planet-ocean/" class="work-card big reveal"><img src="assets/images/watchmaker.webp" alt="Omega Seamaster"><div class="work-overlay"><div><div class="work-title">Omega Seamaster</div><div class="work-meta">Case 01 / service</div></div><span>↗</span></div></a><a href="works/corum-admirals-cup/" class="work-card small reveal"><img src="assets/images/detail-01.webp" alt="Corum"><div class="work-overlay"><div><div class="work-title">Corum Admiral’s Cup</div><div class="work-meta">Case 02</div></div><span>↗</span></div></a><a href="works/maurice-lacroix/" class="work-card small reveal"><img src="assets/images/detail-03.webp" alt="Maurice Lacroix"><div class="work-overlay"><div><div class="work-title">Maurice Lacroix</div><div class="work-meta">Case 03</div></div><span>↗</span></div></a></div><div style="margin-top:42px"><a class="btn" href="works/">Все работы <span class="btn-arrow">→</span></a></div></div></section>

<section class="section section-ivory"><div class="container"><div class="eyebrow reveal">05 / Process</div><h2 class="display display-lg reveal" style="margin:24px 0 0">От состояния<br>к результату.</h2><div class="process-grid">{''.join([f'<div class="process-step reveal"><span class="n">{i+1:02}</span><h3>{title}</h3><p>{text}</p></div>' for i,(title,text) in enumerate([('Диагностика','Определяем состояние часов и характер вмешательства.'),('Согласование','Фиксируем перечень работ до их начала.'),('Работа','Выполняем согласованные операции без лишнего вмешательства.'),('Контроль','Проверяем параметры, относящиеся к выполненной работе.'),('Выдача','Передаём часы владельцу с понятным описанием результата.')])])}</div></div></section>

<section class="section section-dark"><div class="container"><div class="brands-head"><div><div class="eyebrow reveal">06 / The atelier</div><h2 class="display display-lg reveal">Три движения.<br>Одна логика.</h2></div><p class="copy reveal">Вторичные ролики не спрятаны в галерее — они становятся частью ритма страницы: механизм, инструмент, руки мастера.</p></div><div class="video-triptych"><div class="video-tile reveal"><img src="assets/images/detail-01.webp" alt="Механизм"><video autoplay muted loop playsinline poster="assets/images/detail-01.webp"><source src="assets/videos/detail-01.mp4" type="video/mp4"></video><span class="label">Inspection / 01</span></div><div class="video-tile reveal"><img src="assets/images/detail-02.webp" alt="Микроработа"><video autoplay muted loop playsinline poster="assets/images/detail-02.webp"><source src="assets/videos/detail-02.mp4" type="video/mp4"></video><span class="label">Adjustment / 02</span></div><div class="video-tile reveal"><img src="assets/images/detail-03.webp" alt="Браслет"><video autoplay muted loop playsinline poster="assets/images/detail-03.webp"><source src="assets/videos/detail-03.mp4" type="video/mp4"></video><span class="label">Finishing / 03</span></div></div><div style="margin-top:110px"><a class="btn" href="atelier/">Внутри мастерской <span class="btn-arrow">→</span></a></div></div></section>

<section class="section section-navy"><div class="container price-layout"><div class="reveal"><div class="eyebrow">Prices / approval</div><h2 class="display display-md">Цена после понимания задачи.</h2><p class="copy">На старом сайте часть позиций и формулировок пересекается. В новой версии спорные значения намеренно не дублируются: итоговая стоимость должна подтверждаться после диагностики.</p><a class="btn" style="margin-top:28px" href="prices/">Смотреть структуру прайса <span class="btn-arrow">→</span></a></div><div class="price-list reveal"><div class="price-row"><h3>Обслуживание механизма</h3><span>после диагностики</span></div><div class="price-row"><h3>Корпус и полировка</h3><span>по состоянию</span></div><div class="price-row"><h3>Стекло</h3><span>по модели</span></div><div class="price-row"><h3>Герметичность</h3><span>по задаче</span></div><div class="price-row"><h3>Сложные механизмы</h3><span>индивидуально</span></div></div></div></section>

<section class="section section-ivory"><div class="container narrow"><div class="eyebrow reveal">FAQ / Before service</div><h2 class="display display-md reveal" style="margin:24px 0 0">Перед тем как оставить часы.</h2><div class="faq">{faq_html}</div></div></section>

<section class="section section-dark"><div class="container contact-grid"><div class="reveal"><div class="eyebrow">Petrovka · Moscow</div><h2 class="display display-lg contact-title">Мастерская<br>на Петровке.</h2></div><div class="reveal"><dl class="contact-panel"><div class="contact-line"><dt>Адрес</dt><dd>Петровка, Москва<br><span class="small">Номер дома сверить с текущим сайтом перед публикацией.</span></dd></div><div class="contact-line"><dt>График</dt><dd>По предварительной записи<br><span class="small">На старом сайте встречается противоречивый график — требуется подтверждение.</span></dd></div><div class="contact-line"><dt>Связь</dt><dd>Актуальный телефон подставить перед публикацией.</dd></div></dl><div class="contact-actions"><a class="btn" href="contacts/">Записаться <span class="btn-arrow">→</span></a><a class="btn ghost" href="contacts/">Контакты ↗</a></div></div></div></section>
</main>'''
(ROOT/'index.html').write_text(doc('Ремонт швейцарских часов на Петровке — независимая мастерская','Диагностика, обслуживание и восстановление швейцарских часов в Москве. Независимая часовая мастерская на Петровке.',home,0),encoding='utf-8')

# SERVICES INDEX
(ROOT/'services').mkdir(exist_ok=True)
service_cards=''.join([f'''<a class="content-card" href="{slug}/"><div><div class="eyebrow">{i+1:02} / {escape(tag)}</div><h2>{escape(name)}</h2><p>{escape(desc)}</p></div><span>Подробнее ↗</span></a>''' for i,(slug,name,desc,tag) in enumerate(services)])
body=page_hero('Услуги','Service / horology',1,'watchmaker.webp',breadcrumbs([('Услуги',None)],'../'))+f'''<main><section class="section section-dark"><div class="container inner-intro"><div class="eyebrow reveal">Service logic</div><div><p class="lead reveal">От простого вмешательства до сложного калибра — сначала состояние часов, затем решение.</p><p class="copy reveal">Стоимость и объём работ корректно фиксировать после осмотра, а не обещать по одной фотографии.</p></div></div></section><section class="section section-dark" style="padding-top:0"><div class="container content-grid">{service_cards}</div></section></main>'''
(ROOT/'services'/'index.html').write_text(doc('Услуги часовой мастерской — ремонт и обслуживание часов','Полное обслуживание, ремонт механизмов, полировка, стекло, герметичность, автоподзавод и сложные механизмы.',body,1),encoding='utf-8')

for i,(slug,name,desc,tag) in enumerate(services):
    d=ROOT/'services'/slug; d.mkdir(parents=True,exist_ok=True)
    bc=breadcrumbs([('Услуги','../'),(name,None)],'../../')
    body=page_hero(name,tag,2,f'detail-0{(i%3)+1}.webp',bc)+f'''<main><section class="section section-dark"><div class="container detail-layout"><div class="detail-sticky reveal"><img src="../../assets/images/detail-0{(i%3)+1}.webp" alt="{escape(name)}"></div><div class="detail-copy reveal"><div class="eyebrow">Independent service</div><h2>{escape(name)}</h2><p class="lead">{escape(desc)}</p><p>Конкретный объём вмешательства определяется после осмотра. Для часов высокого класса важно сохранить исходную геометрию деталей и не выполнять дополнительные операции без необходимости.</p><ul class="detail-list"><li>Первичный осмотр и фиксация состояния</li><li>Согласование необходимого объёма работ</li><li>Выполнение согласованной операции</li><li>Контроль параметров, связанных с выполненной услугой</li><li>Рекомендации по дальнейшей эксплуатации</li></ul><a class="btn" href="../../contacts/">Записаться на диагностику <span class="btn-arrow">→</span></a></div></div></section><section class="section section-ivory"><div class="container narrow"><div class="eyebrow">Important</div><h2 class="display display-md" style="margin:24px 0">Сначала — часы.<br>Потом — цена.</h2><p class="lead">Цена зависит от модели, состояния и доступности необходимых компонентов. Финальное согласование — до начала основных работ.</p></div></section></main>'''
    d.joinpath('index.html').write_text(doc(f'{name} часов в Москве — часовая мастерская',f'{name}: диагностика и обслуживание в независимой мастерской на Петровке. Стоимость после осмотра.',body,2),encoding='utf-8')

# BRANDS
(ROOT/'brands').mkdir(exist_ok=True)
brand_cards=''.join([f'<a class="brand-index-card" href="{slug}/"><span class="small">{i+1:02} / WATCH MAISON</span><span class="name">{escape(name)}</span><span class="arrow">↗</span></a>' for i,(slug,name) in enumerate(brands)])
body=page_hero('Бренды','Maisons / independent service',1,'hero-poster.webp',breadcrumbs([('Бренды',None)],'../'))+f'''<main><section class="section section-navy"><div class="container"><div class="inner-intro"><div class="eyebrow">Luxury maisons</div><div><p class="lead">От Rolex и Omega до Patek Philippe, Audemars Piguet и Vacheron Constantin.</p><p class="copy">Список используется как навигация по запросам владельцев. Возможность конкретной работы и доступность компонентов подтверждаются после диагностики.</p></div></div><div class="brand-index-grid" style="margin-top:70px">{brand_cards}</div><p class="brands-note">Независимая мастерская. Не является официальным сервисным центром и не аффилирована с указанными производителями. Все товарные знаки принадлежат их правообладателям.</p></div></section></main>'''
(ROOT/'brands'/'index.html').write_text(doc('Ремонт часов Rolex, Patek Philippe, Omega и других брендов','Независимое обслуживание часов ведущих швейцарских и международных мануфактур в Москве.',body,1),encoding='utf-8')
for i,(slug,name) in enumerate(brands):
    d=ROOT/'brands'/slug; d.mkdir(parents=True,exist_ok=True)
    bc=breadcrumbs([('Бренды','../'),(name,None)],'../../')
    body=page_hero(name,'Watch maison / service request',2,f'detail-0{(i%3)+1}.webp',bc)+f'''<main><section class="section section-dark"><div class="container detail-layout"><div class="detail-sticky"><img src="../../assets/images/detail-0{(i%3)+1}.webp" alt="Механизм часов {escape(name)}"></div><div class="detail-copy"><div class="eyebrow">{escape(name)} / Moscow</div><h2>Обслуживание часов {escape(name)}</h2><p class="lead">Диагностика начинается с конкретной модели, состояния и истории часов — не с универсального прайса.</p><p>Для разных калибров, поколений и корпусов перечень возможных работ отличается. Перед началом вмешательства мастерская должна подтвердить техническую возможность ремонта и согласовать объём работ.</p><ul class="detail-list"><li>Диагностика механизма</li><li>Проверка состояния корпуса и внешних элементов</li><li>Согласование ремонта или обслуживания</li><li>Контроль после выполненных работ</li></ul><a class="btn" href="../../contacts/">Запросить диагностику <span class="btn-arrow">→</span></a><p class="small">Независимая мастерская. Упоминание {escape(name)} не означает официальную аффилиацию или авторизацию производителя.</p></div></div></section></main>'''
    d.joinpath('index.html').write_text(doc(f'Ремонт часов {name} в Москве — независимая мастерская',f'Диагностика и обслуживание часов {name} в Москве. Независимая мастерская на Петровке.',body,2),encoding='utf-8')

# WORKS
(ROOT/'works').mkdir(exist_ok=True)
works_cards=''.join([f'''<a class="content-card" href="{slug}/"><div><div class="eyebrow">CASE {i+1:02} / {escape(brand)}</div><h2>{escape(model)}</h2><p>{escape(note)}. Детали старого кейса следует перенести без выдуманных параметров.</p></div><span>Открыть кейс ↗</span></a>''' for i,(slug,brand,model,note) in enumerate(works)])
body=page_hero('Выполненные работы','Selected cases',1,'watchmaker.webp',breadcrumbs([('Работы',None)],'../'))+f'''<main><section class="section section-dark"><div class="container"><div class="inner-intro"><div class="eyebrow">Case studies</div><div><p class="lead">Каждый кейс — отдельная история, а не одинаковая карточка с ценой.</p><p class="copy">В прототип перенесены названия работ, замеченные на исходном сайте. Технические подробности нужно заполнить только фактическими данными.</p></div></div><div class="content-grid" style="margin-top:70px">{works_cards}</div></div></section></main>'''
(ROOT/'works'/'index.html').write_text(doc('Выполненные работы часовой мастерской','Кейсы обслуживания и ремонта швейцарских часов в независимой мастерской.',body,1),encoding='utf-8')
for i,(slug,brand,model,note) in enumerate(works):
    d=ROOT/'works'/slug; d.mkdir(parents=True,exist_ok=True)
    bc=breadcrumbs([('Работы','../'),(f'{brand} {model}',None)],'../../')
    body=page_hero(f'{brand} {model}',f'Case {i+1:02} / selected work',2,f'detail-0{(i%3)+1}.webp',bc)+f'''<main><section class="section section-dark"><div class="container case-grid"><div class="case-copy"><div class="eyebrow">{escape(brand)} / Workshop case</div><h2 class="display display-md">{escape(model)}</h2><p class="copy">{escape(note)}. В текущем прототипе намеренно не выдуманы причина обращения, заменённые детали, сроки или показатели точности.</p><div class="case-specs"><div class="case-spec"><span>Состояние</span><span>Заполнить из исходной карточки</span></div><div class="case-spec"><span>Работы</span><span>Заполнить фактическим перечнем</span></div><div class="case-spec"><span>Контроль</span><span>Указать только реально измеренные параметры</span></div></div><a class="btn" style="margin-top:30px" href="../../contacts/">Записаться <span class="btn-arrow">→</span></a></div><div class="case-media"><img src="../../assets/images/detail-0{(i%3)+1}.webp" alt="{escape(brand)} {escape(model)}"></div></div></section></main>'''
    d.joinpath('index.html').write_text(doc(f'{brand} {model} — кейс часовой мастерской',f'Кейс обслуживания часов {brand} {model}. Независимая мастерская на Петровке.',body,2),encoding='utf-8')

# PRICES
(ROOT/'prices').mkdir(exist_ok=True)
cats=[('Механизм',['Диагностика — после осмотра','Полное обслуживание — после диагностики','Ремонт отдельных узлов — после диагностики','Автоподзавод — после диагностики']),('Корпус и браслет',['Полировка корпуса — после оценки состояния','Сатинирование — после оценки геометрии','Работы с браслетом — по модели']),('Стекло',['Замена стекла — по модели и типу стекла','Посадка и проверка — по задаче']),('Герметичность',['Проверка герметичности — по модели','Замена уплотнений — после осмотра']),('Сложные механизмы',['Хронограф — индивидуально','Турбийон и усложнения — только после предварительной диагностики'])]
price_cats=''.join([f'''<div class="price-category"><button><span>{escape(name)}</span><span>+</span></button><div class="price-category-body">{''.join([f'<div class="price-table-row"><span>{escape(row.split(" — ")[0])}</span><span>{escape(row.split(" — ")[1])}</span></div>' for row in rows])}</div></div>''' for name,rows in cats])
body=page_hero('Цены','Pricing / approval first',1,'detail-01.webp',breadcrumbs([('Цены',None)],'../'))+f'''<main><section class="section section-navy"><div class="container price-layout"><div><div class="eyebrow">Pricing logic</div><h2 class="display display-md">Без фальшивой точности.</h2><p class="copy">На старом сайте обнаружены пересекающиеся названия и значения. Поэтому здесь оставлена корректная структура прайса без спорных цифр. Перед публикацией значения нужно сверить и внести один раз.</p></div><div class="price-accordion">{price_cats}</div></div></section></main>'''
(ROOT/'prices'/'index.html').write_text(doc('Цены на ремонт и обслуживание часов','Структура стоимости обслуживания часов: механизм, корпус, стекло, герметичность и сложные калибры.',body,1),encoding='utf-8')

# ATELIER
(ROOT/'atelier').mkdir(exist_ok=True)
body=page_hero('Мастерская','The atelier / craft',1,'watchmaker.webp',breadcrumbs([('Мастерская',None)],'../'))+'''<main><section class="section section-dark"><div class="container craft-grid"><div class="media-frame"><img src="../assets/images/watchmaker.webp" alt="Часовщик за работой"><video autoplay muted loop playsinline poster="../assets/images/watchmaker.webp"><source src="../assets/videos/watchmaker.mp4" type="video/mp4"></video><div class="media-caption"><span>Manual work / macro</span><span>01</span></div></div><div class="craft-copy"><div><div class="eyebrow">Precision over decoration</div><h2 class="display display-md">Мастерская должна доказывать себя процессом.</h2><p class="copy">Не сертификатами, которых пользователь не видел, и не словами «премиум». В кадре — руки, инструмент и реальная механика.</p></div><p class="small">Перед публикацией сюда стоит добавить реальные фотографии рабочего места, оборудования и мастера — без стоковых изображений.</p></div></div></section><section class="section section-ivory"><div class="container"><div class="eyebrow">Micro operations</div><h2 class="display display-lg" style="margin:24px 0">Точность в трёх кадрах.</h2><div class="video-triptych"><div class="video-tile"><video autoplay muted loop playsinline poster="../assets/images/detail-01.webp"><source src="../assets/videos/detail-01.mp4" type="video/mp4"></video><span class="label">Inspection</span></div><div class="video-tile"><video autoplay muted loop playsinline poster="../assets/images/detail-02.webp"><source src="../assets/videos/detail-02.mp4" type="video/mp4"></video><span class="label">Adjustment</span></div><div class="video-tile"><video autoplay muted loop playsinline poster="../assets/images/detail-03.webp"><source src="../assets/videos/detail-03.mp4" type="video/mp4"></video><span class="label">Finishing</span></div></div></div></section></main>'''
(ROOT/'atelier'/'index.html').write_text(doc('Часовая мастерская на Петровке','Независимая часовая мастерская: процесс обслуживания, работа мастера и макросъёмка механики.',body,1),encoding='utf-8')

# CONTACTS
(ROOT/'contacts').mkdir(exist_ok=True)
body=page_hero('Контакты','Petrovka / Moscow',1,'hero-poster.webp',breadcrumbs([('Контакты',None)],'../'))+'''<main><section class="section section-dark"><div class="container contact-grid"><div><div class="eyebrow">Visit / appointment</div><h2 class="display display-md">Петровка,<br>Москва.</h2><p class="copy">Для часов высокого класса удобнее предварительно описать модель и задачу. Контактные данные ниже намеренно требуют финальной сверки с владельцем сайта.</p></div><div><dl class="contact-panel"><div class="contact-line"><dt>Адрес</dt><dd>Петровка, Москва<br><span class="small">TODO: подставить точный номер дома.</span></dd></div><div class="contact-line"><dt>Телефон</dt><dd>TODO: актуальный телефон мастерской</dd></div><div class="contact-line"><dt>График</dt><dd>TODO: подтвердить единый график — старый сайт содержит разные варианты.</dd></div></dl><form class="contact-form" data-demo-form><input class="field" required placeholder="Имя"><input class="field" required placeholder="Телефон"><input class="field" placeholder="Марка и модель часов"><textarea class="field" placeholder="Что произошло с часами?"></textarea><button class="btn" type="submit">Оставить заявку <span class="btn-arrow">→</span></button><div class="form-note">Демо-форма. Перед публикацией подключите её к CRM, почте или мессенджеру.</div></form></div></div></section></main>'''
(ROOT/'contacts'/'index.html').write_text(doc('Контакты часовой мастерской на Петровке','Запись на диагностику и обслуживание часов в независимой мастерской на Петровке в Москве.',body,1),encoding='utf-8')

print('Built', ROOT)
